#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Project_4.Resource", IsApplication=true)]

namespace Project_4
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Project_4.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Project_4.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Arm_2 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ArmOef1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ArmOef2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ArmOef3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Been_3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int BeenOef1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int BeenOef2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int BeenOef3 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int BMI_4 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Borst_5 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int BorstOef1 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int BorstOef2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int BorstOef3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Buik_6 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int BuikOef1 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int BuikOef2 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int BuikOef3 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int check_1 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Logo_6 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Settings_4 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Tabel1 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Thuisoefeningen_2 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Thuisoefeningen_9 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Timer_5 = 2130837527;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int Button1 = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int Button2 = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int Button3 = 2131034123;
			
			// aapt resource value: 0x7f05000f
			public const int InputHeight = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int InputWeight = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int OutputResult = 2131034129;
			
			// aapt resource value: 0x7f05002e
			public const int btnStart = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int btnStop = 2131034159;
			
			// aapt resource value: 0x7f050018
			public const int buAdd = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int buDelete = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int buSelect = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int buUpdate = 2131034138;
			
			// aapt resource value: 0x7f05000c
			public const int button1 = 2131034124;
			
			// aapt resource value: 0x7f050010
			public const int buttonCalculate = 2131034128;
			
			// aapt resource value: 0x7f050030
			public const int editText1 = 2131034160;
			
			// aapt resource value: 0x7f050015
			public const int etDate = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int etFullName = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int etWeight = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int etid = 2131034132;
			
			// aapt resource value: 0x7f050012
			public const int imageButton1 = 2131034130;
			
			// aapt resource value: 0x7f050023
			public const int imageButton2 = 2131034147;
			
			// aapt resource value: 0x7f050026
			public const int imageButton3 = 2131034150;
			
			// aapt resource value: 0x7f050029
			public const int imageButton4 = 2131034153;
			
			// aapt resource value: 0x7f05001e
			public const int imageButton5 = 2131034142;
			
			// aapt resource value: 0x7f050001
			public const int imageView1 = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int imageView2 = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int imageView3 = 2131034121;
			
			// aapt resource value: 0x7f050017
			public const int linearLayout1 = 2131034135;
			
			// aapt resource value: 0x7f05002c
			public const int progressView = 2131034156;
			
			// aapt resource value: 0x7f05000d
			public const int scrollView1 = 2131034125;
			
			// aapt resource value: 0x7f05002b
			public const int spinner1 = 2131034155;
			
			// aapt resource value: 0x7f050022
			public const int tableRow1 = 2131034146;
			
			// aapt resource value: 0x7f05002a
			public const int tableRow10 = 2131034154;
			
			// aapt resource value: 0x7f050024
			public const int tableRow2 = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int tableRow3 = 2131034149;
			
			// aapt resource value: 0x7f050027
			public const int tableRow4 = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int tableRow5 = 2131034152;
			
			// aapt resource value: 0x7f050021
			public const int tableRow6 = 2131034145;
			
			// aapt resource value: 0x7f050020
			public const int tableRow7 = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int tableRow8 = 2131034143;
			
			// aapt resource value: 0x7f05001d
			public const int tableRow9 = 2131034141;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int textView2 = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int textView3 = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int textView4 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int textView5 = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int textView6 = 2131034122;
			
			// aapt resource value: 0x7f05001c
			public const int tvViewText = 2131034140;
			
			// aapt resource value: 0x7f05002d
			public const int txtTimer = 2131034157;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ArmOefeningen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Armvid = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Armvid2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Armvid3 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Beenoefeningen = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Beenvid = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Beenvid2 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Beenvid3 = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int BmiApp = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Borstoefeningen = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Borstvid = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Borstvid2 = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Borstvid3 = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Buikoefeningen = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Buikvid = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Buikvid2 = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int Buikvid3 = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int DB = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int Hoofdmenu = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Schema = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Thuisoefeningen = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Timer = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int ToDolijst = 2130903062;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
